import Head from 'next/head'
// import { baseUrl, fetchApi } from '../utils/fetchApi';
import axios from "axios";
import { useState } from 'react';

import Header from '../components/Header'

export default function Home({ data }) {
  // console.log(data);
  return (
    <div className=''>
      <Head>
        <title>K's Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <div className='w-[90%] mx-auto '>
        <div>
          <img src={data.image_url} alt=" " className='w-40 rounded-md' />
        </div>
        <p className='my-2'>
          Profile Name: {data.name}
        </p>
        <p className='my-2'>
          Following: {data.following_count}
        </p>
      </div>

      <div className='w-[90%] mx-auto '>
        <h3>
          Public Playlist
        </h3>
        <div>
          {
            data.public_playlists.map((index, playlist) => (
              <div>
                
              </div>
            ))
          }
        </div>
      </div>
      
    </div>
  )
}


export async function getStaticProps() {
  const res = await axios.get(
    'https://spotify23.p.rapidapi.com/user_profile/',
  {
    params: {id: '6ifbujr7hgpu5mqie68473zgx', playlistLimit: '10', artistLimit: '10'},
    headers: {
      'X-RapidAPI-Key': 'c7d1a728c2msh9230e16f814ef0bp176af4jsna038481202cc',
      'X-RapidAPI-Host': 'spotify23.p.rapidapi.com'
    }
  }
  )

  const { data } = res

  return {
    props: {
      data,
    }
  }
}