import Head from 'next/head'
import axios from "axios";
import Header from '../components/Header'

export default function Home({ data }) {
  return (
    <div className=''>
      <Head>
        <title>K's Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <div className='w-[90%] mx-auto '>
        <div>
          <img src={data.image_url} alt=" " className='w-40 rounded-md' />
        </div>
        <p className='my-2'>
          Profile Name: {data.name}
        </p>
        <p className='my-2'>
          Following: {data.following_count}
        </p>
      </div>

      <div className='w-[90%] mx-auto '>
        <h3>
          Public Playlist
        </h3>
        <div className='grid grid-cols-2 md:grid-cols-4 gap-8 py-8'>
          {
            data.public_playlists.map((playlist) => {
              const playlistId = playlist.uri.slice(17, -1)
            return (
              <div className='text-white shadow-md shadow-gray-800 rounded-md hover:scale-105 transition-all duration-200 ease-in-out' key={playlist.uri}>
                <a href={`https://open.spotify.com/playlist/${playlistId}`} target="_blank" rel='noreferrer'>
                <div className='bg-green-600/20 h-60 w-full rounded-t-md' />
                <p className='px-3 py-1 font-medium'>
                  {playlist.name}
                </p>
                </a>
              </div>
            )
          })
          }
        </div>
      </div>
      
    </div>
  )
}


export async function getStaticProps() {
  const res = await axios.get(
    'https://spotify23.p.rapidapi.com/user_profile/',
  {
    params: {id: '6ifbujr7hgpu5mqie68473zgx', playlistLimit: '10', artistLimit: '10'},
    headers: {
      'X-RapidAPI-Key': process.env.NEXT_PUBLIC_RAPID_API_KEY,
      'X-RapidAPI-Host': 'spotify23.p.rapidapi.com'
    }
  }
  )

  const { data } = res

  return {
    props: {
      data,
    }
  }
}